LacysMobile/LacysMobile/Controllers/CustomerController.cs
using LacysMobile.Web.Binders;
using LacysMobile.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LacysMobile.Web.Controllers
{
    public class CustomerController : Controller
    {
        ShoppingCartModel cart = (ShoppingCartModel)CartModelBinder.getSession();

        public ActionResult CustomerPage()
        {
            ViewBag.ItemCount = cart.ItemCount;
            ViewBag.Header = "Customer Portal";

            return View();
        }
	}
}

LacysMobile/LacysMobile/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LacysMobile.Data;
using LacysMobile.Models;
using LacysMobile.Web.Models;
using LacysMobile.Web.Binders;


namespace LacysMobile.Web.Controllers
{
    public class ProductsController : Controller
    {
        ShoppingCartModel cart = (ShoppingCartModel)CartModelBinder.getSession();

        private UnitOfWork _uow = new UnitOfWork();

        public ActionResult Category(string itemType)
        {
            string headerName = "";
            List<Product> model = new List<Product>();
 
            switch (itemType)
            {
                case "WomenDress":
                    model = GetCategories(model, "WomenDress");
                    headerName = "Women's Dresses";
                    break;
                case "WomenCoats":
                    model = GetCategories(model, "WomenCoats");
                    headerName = "Women's Coats";
                    break;
                case "MenPants":
                    model = GetCategories(model, "MensPants");
                    headerName = "Men's Pants";
                    break;
                case "MenCoats":
                    model = GetCategories(model, "MenCoats");
                    headerName = "Men's Coats";
                    break;
                case "Handbags":
                    model = GetCategories(model, "Handbags");
                    headerName = "Handbags";
                    break;
                default: // "Sunglasses"
                    model = GetCategories(model, "Sunglasses");
                    headerName = "Sunglasses";
                    break;
            }

            ViewBag.Header = headerName;
            ViewBag.ItemCount = cart.ItemCount;
            return View(model);
        }

        private List<Product> GetCategories(List<Product> model, string category)
        {
            List<Product> womensDressList = this._uow.Products.GetAll().Where(p => p.ItemType == category).ToList();
            foreach (var product in womensDressList)
            {
                model.Add(new Product
                {
                    Name = product.Name,
                    ImageName = product.ImageName,
                    ProductID = product.ProductID,
                    Description = product.Description,
                    SellingPrice = product.SellingPrice
                });
            }

            return model;
        }

        public ActionResult Product(int id)
        {
            Product model = this._uow.Products.GetById(id);

            // read review
            List<ProductReview> reviewList = new List<ProductReview>();
            reviewList = this._uow.ProductReviews.GetAll().Where(r => r.ProductFK == id).ToList();

            foreach (var review in reviewList)
            {
                review.Date = review.ReviewDate.ToShortDateString();
            }

            ViewBag.ReviewModel = reviewList;

            ViewBag.Header = model.Name;
            ViewBag.ItemCount = cart.ItemCount;

            return View(model);
        }

        [HttpPost]
        public ActionResult AddToCart(FormCollection product)
        {
            int productId = Convert.ToInt32(product["productId"]);
            int productQuantity = Convert.ToInt32(product["productQuantity"]);
            decimal sellingPrice = Convert.ToDecimal(product["sellingPrice"]);
            string productName = product["productName"];

            cart.AddShoppingCartItem(productId, productQuantity, sellingPrice, productName);
            return RedirectToAction("Product", new { id = productId });           
        } 


    }
}

LacysMobile/LacysMobile/Views/Shared/_AccountNavLinks.cshtml
<li>
    @if (User.Identity.IsAuthenticated)
    {
        @Html.ActionLink("Sign Out", "LogOff", "Account")
    }
    else
    {
        @Html.ActionLink("Sign In", "Login", "Account")
    }
</li>
<li>
    @if (!User.Identity.IsAuthenticated)
    {
        @Html.ActionLink("Register", "Register", "Account")
    }
</li>
<li class="dropdown">
    @if (User.Identity.IsAuthenticated)
    {
        <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="manage-account">Manage Account <span class="caret"></span></a>
    
        <ul class="dropdown-menu" aria-labelledby="themes">
            <li>@Html.ActionLink("Update Profile", "UpdateProfile", "Account")</li>
            <li class="divider"></li>
            <li>@Html.ActionLink("Change Password", "ChangePassword", "Account")</li>
        </ul>
    }
</li>
<li>
    @if (User.Identity.IsAuthenticated && User.IsInRole("Employee"))
    {
        @Html.ActionLink("Employee Portal", "EmployeePage", "Employee")
    }
    else if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
    {
        @Html.ActionLink("Administrator Portal", "AdministratorPage", "Administrator")
    }
    else if (User.Identity.IsAuthenticated)
    {
        @*@Html.ActionLink("Customer Portal", "CustomerPage", "Customer")*@
        <a href="#">Customer Portal</a>
    }
</li>

LacysMobile/LacysMobile/Views/Shared/_Footer.cshtml
<br/>
<hr/>
    <div class="row">
        <div class="col-lg-12">

            <ul class="list-unstyled">
                <li class="pull-right"><a href="#top">Back to top</a></li>
                <li><a href="http://www.gwinnetttech.edu/">Gwinnett Tech</a></li>
            </ul>
            <p><h6>&copy;2014 Lacy's Retail Stores Inc.</h6></p>

        </div>
    </div>

LacysMobile/LacysMobile/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width" />

    @Styles.Render("~/Content/Bootstrap")
    @Styles.Render("~/Content/Bootstrap/BootstrapTheme")
    @Styles.Render("~/Content/Layout")
    @Scripts.Render("/bundles/jquery")
    @Scripts.Render("/bundles/jquerymobile")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            @Html.Partial("_Navbar")
        </div>
    </div>
    <div class="container">
        @RenderBody()
    </div>
    <div class="footer-details">
        <div class="container">
            @Html.Partial("_Footer")
        </div>
    </div>

    @RenderSection("scripts", required: false)
    @Scripts.Render("~/bundles/Bootstrap")
</body>
</html>

LacysMobile/LacysMobile/Views/Shared/_Navbar.cshtml
<div class="navbar-header">
    <a href="/Home" class="navbar-brand logo"></a>
    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <span class="shopping-cart-icon">
        <a href="/Cart/Checkout" class="navbar-brand glyphicon glyphicon-shopping-cart">
            <span class="badge"><span class="badge-number">@ViewBag.ItemCount</span></span>
        </a>
    </span>
</div>

<div class="navbar-collapse collapse" id="navbar-main">
    <ul class="nav navbar-nav">
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="shop-by-category">Shop by Category <span class="caret"></span></a>
            <ul class="dropdown-menu" aria-labelledby="themes">
                <li>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="womens-clothing">Women's Clothing</a>
                    <ul>
                        <li>@Html.ActionLink("Dresses", "Category", "Products", new { itemType = "WomenDress" }, new { Class = "navbar-link" })</li>
                        <li>@Html.ActionLink("Coats", "Category", "Products", new { itemType = "WomenCoats" }, new { Class = "navbar-link" })</li>
                    </ul>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="mens-clothing">Men's Clothing</a>
                    <ul>
                        <li>@Html.ActionLink("Pants", "Category", "Products", new { itemType = "MenPants" }, new { Class = "navbar-link" })</li>
                        <li>@Html.ActionLink("Coats", "Category", "Products", new { itemType = "MenCoats" }, new { Class = "navbar-link" })</li>
                    </ul>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="accessories">Accessories</a>
                    <ul>
                        <li>@Html.ActionLink("Handbags", "Category", "Products", new { itemType = "Handbags" }, new { Class = "navbar-link" })</li>
                        <li>@Html.ActionLink("Sunglasses", "Category", "Products", new { itemType = "Sunglasses" }, new { Class = "navbar-link" })</li>
                    </ul>
                    <li class="divider"></li>
            </ul>
        </li>
        <li>
            @Html.ActionLink("Feedback", "FeedbackForm", "Feedback")
        </li>
        @Html.Partial("_AccountNavLinks")
    </ul>

</div>